[package]
name = "rust-cmd-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(linux)'.dependencies]
ncurses = "5.101.0"
